In [234]:
import numpy as np
import collections
from sklearn.model_selection import train_test_split
from scipy.io import loadmat

In [253]:
d = loadmat('MNIST784x50x10.mat')
d.keys()

dict_keys(['__header__', '__version__', '__globals__', 'X', 'index'])

In [254]:
x = d['X'].T
y = d['index'][0].reshape(500,1)


In [255]:
result = 'k值,轮次,分类正确样本数,准确率,均方差\n'

In [256]:
for k in [1, 20, 50]:
    acc_total = 0
    delta_total = 0
    for j in range(10):
        x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.5)
        test_num = len(x_test)
        y_predict = np.zeros(test_num)
        for i in range(test_num):
            distance = np.sum(np.square(x_train - x_test[i,:]), axis=1)
            nearest_idx = np.argpartition(distance, k-1)[0:k]
            votes = np.squeeze(y_train[nearest_idx])
            if k == 1:
                votes = np.array([votes])
            y_predict[i] = np.argmax(np.bincount(votes))
        y_test = np.squeeze(y_test)
        num = np.sum(y_predict==y_test)
        acc = np.sum(y_predict==y_test)/y_predict.shape[0]
        delta = (np.sum((y_predict-y_test)**2)/y_predict.shape[0])**(1/2)
        acc_total += acc
        delta_total += delta
        result = result + str(k) + ',' + str(j) + ',' + str(num) + ',' + str(acc) + ',' + str(delta) + '\n'
        print(k, j, num, acc, delta)
    result = result + str(k) + ',' + ',' +  ',' + str(acc_total/10) + ',' + str(delta_total/10) + '\n'
    print(k, acc_total/10, delta_total/10)

with open('knn_minist.csv', 'w') as f:
    f.write(result)


1 0 49 0.196 3.682933613303395
1 1 55 0.22 3.112555220393688
1 2 46 0.184 3.356188314144485
1 3 39 0.156 3.565950083778515
1 4 55 0.22 4.0009998750312405
1 5 53 0.212 3.6529440181858797
1 6 48 0.192 3.443835071544513
1 7 39 0.156 3.9683749822817904
1 8 56 0.224 3.5270384177096794
1 9 57 0.228 3.7619144062564738
1 0.1988 3.6072734002629665
20 0 27 0.108 5.165268628057984
20 1 27 0.108 5.359104402789705
20 2 36 0.144 5.149757275833493
20 3 24 0.096 5.426969688509417
20 4 28 0.112 5.331041174104736
20 5 24 0.096 5.2642188404358725
20 6 27 0.108 5.419963099505384
20 7 26 0.104 5.282045058497703
20 8 30 0.12 5.245569559161331
20 9 21 0.084 5.435439264677695
20 0.10799999999999998 5.307937699157332
50 0 28 0.112 5.258136552049595
50 1 45 0.18 5.048564152311031
50 2 29 0.116 5.519420259411309
50 3 28 0.112 5.4808758424178885
50 4 24 0.096 5.541119020558934
50 5 38 0.152 5.109598810082843
50 6 25 0.1 5.5533773507659285
50 7 27 0.108 5.413316912947181
50 8 23 0.092 5.310743827374844
50 9 19 0.0

In [257]:
result = 'k值,轮次,分类正确样本数,准确率,均方差\n'

In [258]:
for k in [1, 20, 50]:
    acc_total = 0
    delta_total = 0
    for j in range(10):
        x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.5)
        test_num = len(x_test)
        y_predict = np.zeros(test_num)
        for i in range(test_num):
            distance = np.sum(np.square(x_train - x_test[i,:]), axis=1)
            nearest_idx = np.argpartition(distance, [0, k-1])[0:k]
            votes = np.squeeze(y_train[nearest_idx])
            if k !=1:
                d1=distance[nearest_idx[0]]
                dk=distance[nearest_idx[k-1]]
                k_distance = distance[nearest_idx]
                w = (dk-k_distance)/(dk-d1)          
            else:
                votes = np.array([votes])
                w = np.array([1])
            y_predict[i] = np.argmax(np.bincount(votes, weights=w))
        y_test = np.squeeze(y_test)
        num = np.sum(y_predict==y_test)
        acc = np.sum(y_predict==y_test)/y_predict.shape[0]
        delta = (np.sum((y_predict-y_test)**2)/y_predict.shape[0])**(1/2)
        acc_total += acc
        delta_total += delta
        result = result + str(k) + ',' + str(j) + ',' + str(num) + ',' + str(acc) + ',' + str(delta) + '\n'
        print(k, j, num, acc, delta)
    result = result + str(k) + ',' + ',' +  ',' + str(acc_total/10) + ',' + str(delta_total/10) + '\n'
    print(k, acc_total/10, delta_total/10)
with open('knn_minist1.csv', 'w') as f:
    f.write(result)

1 0 55 0.22 3.8194240403495394
1 1 57 0.228 3.789986807364902
1 2 54 0.216 3.057449917823676
1 3 48 0.192 3.6513011379506897
1 4 47 0.188 3.6753231150471652
1 5 55 0.22 3.02787053884409
1 6 47 0.188 3.9425879825312715
1 7 44 0.176 3.2526911934581184
1 8 57 0.228 3.22490309931942
1 9 37 0.148 4.355226744958292
1 0.2004 3.579676457764717
20 0 42 0.168 5.183435154412564
20 1 31 0.124 5.205381830375174
20 2 48 0.192 4.238867773356466
20 3 31 0.124 5.025534797412112
20 4 33 0.132 5.147037983151086
20 5 43 0.172 4.92909728043584
20 6 32 0.128 5.149368893369361
20 7 39 0.156 5.149368893369361
20 8 43 0.172 4.0501851809516065
20 9 25 0.1 5.392216612859688
20 0.14679999999999999 4.947049439969327
50 0 29 0.116 5.347896782848375
50 1 31 0.124 5.143928459844674
50 2 32 0.128 5.348270748569111
50 3 25 0.1 5.48014598345701
50 4 26 0.104 5.3467747287500345
50 5 14 0.056 5.2497618993626745
50 6 27 0.108 5.1377037672485555
50 7 22 0.088 5.308107007210762
50 8 32 0.128 5.376988004450075
50 9 23 0.092 5

In [259]:
result = 'k值,轮次,分类正确样本数,准确率,均方差\n'

In [260]:
from cvxopt import matrix, solvers


for k in [1, 20, 50]:
    acc_total = 0
    delta_total = 0
    for j in range(10):
        
        x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.5)
        test_num = len(x_test)
        y_predict = np.zeros(test_num)
        for i in range(test_num):
            distance = np.sum(np.square(x_train - x_test[i,:]), axis=1)
            nearest_idx = np.argpartition(distance, [0, k-1])[0:k]
            k_neighbors = x_train[nearest_idx]
            distance = np.sum(np.square(k_neighbors - x_test[i,:]), axis=1)

            p=np.zeros((k, k))
            q=np.zeros((k, 1))
            for m in range(k):
                q[m][0] = -2*np.sum(k_neighbors[m,:] * x_test[i,:])
                for n in range(k):
                    p[m][n] = 2*np.sum(k_neighbors[m,:] * k_neighbors[n,:])

            g = -1*np.identity(k)
            h = np.zeros((k, 1))
            a = np.ones((1,k))
            P=matrix(p)
            q=matrix(q)
            G=matrix(g)
            h=matrix(h)
            A=matrix(a)
            b=matrix([1.0])
            w=np.squeeze(solvers.qp(P,q,G,h,A,b)['x'])
            votes = np.squeeze(y_train[nearest_idx])
            if k == 1:
                votes = np.array([votes])
                w = np.array([1])
            y_predict[i] = np.argmax(np.bincount(votes, weights=w))
        y_test = np.squeeze(y_test)
        num = np.sum(y_predict==y_test)
        acc = np.sum(y_predict==y_test)/y_predict.shape[0]
        delta = (np.sum((y_predict-y_test)**2)/y_predict.shape[0])**(1/2)
        acc_total += acc
        delta_total += delta
        result = result + str(k) + ',' + str(j) + ',' + str(num) + ',' + str(acc) + ',' + str(delta) + '\n'
        print(k, j, num, acc, delta)
    result = result + str(k) + ',' + ',' +  ',' + str(acc_total/10) + ',' + str(delta_total/10) + '\n'
    print(k, acc_total/10, delta_total/10)
with open('knn_minist2.csv', 'w') as f:
    f.write(result)


     pcost       dcost       gap    pres   dres
 0: -9.5260e+03 -9.5270e+03  1e+00  2e-16  2e-04
 1: -9.5260e+03 -9.5260e+03  1e-02  2e-16  2e-06
 2: -9.5260e+03 -9.5260e+03  1e-04  0e+00  2e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -1.1006e+04 -1.1007e+04  1e+00  7e-16  2e-04
 1: -1.1006e+04 -1.1006e+04  1e-02  3e-16  2e-06
 2: -1.1006e+04 -1.1006e+04  1e-04  1e-16  2e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -5.8230e+03 -5.8240e+03  1e+00  4e-16  3e-04
 1: -5.8230e+03 -5.8230e+03  1e-02  2e-16  3e-06
 2: -5.8230e+03 -5.8230e+03  1e-04  0e+00  3e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -5.5150e+03 -5.5160e+03  1e+00  2e-16  3e-04
 1: -5.5150e+03 -5.5150e+03  1e-02  3e-16  3e-06
 2: -5.5150e+03 -5.5150e+03  1e-04  3e-16  3e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -1.2781e+04 -1.2782e+04  1e+00  0e+00  1e-04
 1: -1.2781e+04 -1.2781e+04

 2: -9.4930e+03 -9.4930e+03  1e-04  3e-16  2e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -6.4930e+03 -6.4940e+03  1e+00  1e-16  3e-04
 1: -6.4930e+03 -6.4930e+03  1e-02  3e-16  3e-06
 2: -6.4930e+03 -6.4930e+03  1e-04  3e-16  3e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -8.7030e+03 -8.7040e+03  1e+00  4e-16  2e-04
 1: -8.7030e+03 -8.7030e+03  1e-02  2e-16  2e-06
 2: -8.7030e+03 -8.7030e+03  1e-04  0e+00  2e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -9.6130e+03 -9.6140e+03  1e+00  4e-16  2e-04
 1: -9.6130e+03 -9.6130e+03  1e-02  2e-16  2e-06
 2: -9.6130e+03 -9.6130e+03  1e-04  0e+00  2e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -1.3841e+04 -1.3842e+04  1e+00  2e-16  1e-04
 1: -1.3841e+04 -1.3841e+04  1e-02  2e-16  1e-06
 2: -1.3841e+04 -1.3841e+04  1e-04  0e+00  1e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0:

     pcost       dcost       gap    pres   dres
 0: -1.1734e+04 -1.1735e+04  1e+00  0e+00  1e-04
 1: -1.1734e+04 -1.1734e+04  1e-02  1e-16  1e-06
 2: -1.1734e+04 -1.1734e+04  1e-04  3e-16  1e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -1.0261e+04 -1.0262e+04  1e+00  7e-16  2e-04
 1: -1.0261e+04 -1.0261e+04  1e-02  3e-16  2e-06
 2: -1.0261e+04 -1.0261e+04  1e-04  1e-16  2e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -7.8690e+03 -7.8700e+03  1e+00  0e+00  2e-04
 1: -7.8690e+03 -7.8690e+03  1e-02  1e-16  2e-06
 2: -7.8690e+03 -7.8690e+03  1e-04  3e-16  2e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -9.6670e+03 -9.6680e+03  1e+00  1e-16  2e-04
 1: -9.6670e+03 -9.6670e+03  1e-02  3e-16  2e-06
 2: -9.6670e+03 -9.6670e+03  1e-04  3e-16  2e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -1.8216e+04 -1.8217e+04  1e+00  4e-16  1e-04
 1: -1.8216e+04 -1.8216e+04

     pcost       dcost       gap    pres   dres
 0: -1.3739e+04 -1.3740e+04  1e+00  4e-16  1e-04
 1: -1.3739e+04 -1.3739e+04  1e-02  2e-16  1e-06
 2: -1.3739e+04 -1.3739e+04  1e-04  0e+00  1e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -1.1834e+04 -1.1835e+04  1e+00  3e-16  1e-04
 1: -1.1834e+04 -1.1834e+04  1e-02  0e+00  1e-06
 2: -1.1834e+04 -1.1834e+04  1e-04  1e-16  1e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -3.0240e+03 -3.0250e+03  1e+00  0e+00  4e-04
 1: -3.0240e+03 -3.0240e+03  1e-02  1e-16  4e-06
 2: -3.0240e+03 -3.0240e+03  1e-04  3e-16  4e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -1.4226e+04 -1.4227e+04  1e+00  2e-16  1e-04
 1: -1.4226e+04 -1.4226e+04  1e-02  2e-16  1e-06
 2: -1.4226e+04 -1.4226e+04  1e-04  0e+00  1e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -6.9150e+03 -6.9160e+03  1e+00  0e+00  2e-04
 1: -6.9150e+03 -6.9150e+03

     pcost       dcost       gap    pres   dres
 0: -1.4230e+04 -1.4231e+04  1e+00  0e+00  1e-04
 1: -1.4230e+04 -1.4230e+04  1e-02  1e-16  1e-06
 2: -1.4230e+04 -1.4230e+04  1e-04  3e-16  1e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -8.6810e+03 -8.6820e+03  1e+00  1e-16  2e-04
 1: -8.6810e+03 -8.6810e+03  1e-02  3e-16  2e-06
 2: -8.6810e+03 -8.6810e+03  1e-04  3e-16  2e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -6.8560e+03 -6.8570e+03  1e+00  1e-16  2e-04
 1: -6.8560e+03 -6.8560e+03  1e-02  3e-16  2e-06
 2: -6.8560e+03 -6.8560e+03  1e-04  3e-16  2e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -1.3470e+04 -1.3471e+04  1e+00  0e+00  1e-04
 1: -1.3470e+04 -1.3470e+04  1e-02  1e-16  1e-06
 2: -1.3470e+04 -1.3470e+04  1e-04  3e-16  1e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -8.1370e+03 -8.1380e+03  1e+00  2e-16  2e-04
 1: -8.1370e+03 -8.1370e+03

     pcost       dcost       gap    pres   dres
 0: -6.8980e+03 -6.8990e+03  1e+00  1e-16  2e-04
 1: -6.8980e+03 -6.8980e+03  1e-02  3e-16  2e-06
 2: -6.8980e+03 -6.8980e+03  1e-04  3e-16  2e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -1.1408e+04 -1.1409e+04  1e+00  1e-16  1e-04
 1: -1.1408e+04 -1.1408e+04  1e-02  3e-16  1e-06
 2: -1.1408e+04 -1.1408e+04  1e-04  3e-16  1e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -7.4410e+03 -7.4420e+03  1e+00  4e-16  2e-04
 1: -7.4410e+03 -7.4410e+03  1e-02  2e-16  2e-06
 2: -7.4410e+03 -7.4410e+03  1e-04  0e+00  2e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -1.0096e+04 -1.0097e+04  1e+00  2e-16  2e-04
 1: -1.0096e+04 -1.0096e+04  1e-02  2e-16  2e-06
 2: -1.0096e+04 -1.0096e+04  1e-04  0e+00  2e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -1.1734e+04 -1.1735e+04  1e+00  0e+00  1e-04
 1: -1.1734e+04 -1.1734e+04

     pcost       dcost       gap    pres   dres
 0: -1.5957e+04 -1.5958e+04  1e+00  2e-16  1e-04
 1: -1.5957e+04 -1.5957e+04  1e-02  3e-16  1e-06
 2: -1.5957e+04 -1.5957e+04  1e-04  3e-16  1e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -1.0150e+04 -1.0151e+04  1e+00  1e-16  2e-04
 1: -1.0150e+04 -1.0150e+04  1e-02  3e-16  2e-06
 2: -1.0150e+04 -1.0150e+04  1e-04  3e-16  2e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -8.4850e+03 -8.4860e+03  1e+00  2e-16  2e-04
 1: -8.4850e+03 -8.4850e+03  1e-02  2e-16  2e-06
 2: -8.4850e+03 -8.4850e+03  1e-04  0e+00  2e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -7.4470e+03 -7.4480e+03  1e+00  0e+00  1e-04
 1: -7.4470e+03 -7.4470e+03  1e-02  1e-16  1e-06
 2: -7.4470e+03 -7.4470e+03  1e-04  3e-16  1e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -8.2960e+03 -8.2970e+03  1e+00  0e+00  2e-04
 1: -8.2960e+03 -8.2960e+03

 2: -9.8590e+03 -9.8590e+03  1e-04  0e+00  2e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -4.5110e+03 -4.5120e+03  1e+00  0e+00  3e-04
 1: -4.5110e+03 -4.5110e+03  1e-02  1e-16  3e-06
 2: -4.5110e+03 -4.5110e+03  1e-04  3e-16  3e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -7.4450e+03 -7.4460e+03  1e+00  2e-16  2e-04
 1: -7.4450e+03 -7.4450e+03  1e-02  3e-16  2e-06
 2: -7.4450e+03 -7.4450e+03  1e-04  3e-16  2e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -3.7710e+03 -3.7720e+03  1e+00  1e-16  4e-04
 1: -3.7710e+03 -3.7710e+03  1e-02  3e-16  4e-06
 2: -3.7710e+03 -3.7710e+03  1e-04  3e-16  4e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -1.2523e+04 -1.2524e+04  1e+00  2e-16  1e-04
 1: -1.2523e+04 -1.2523e+04  1e-02  3e-16  1e-06
 2: -1.2523e+04 -1.2523e+04  1e-04  3e-16  1e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0:

 2: -8.2910e+03 -8.2910e+03  1e-04  3e-16  2e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -6.9590e+03 -6.9600e+03  1e+00  0e+00  2e-04
 1: -6.9590e+03 -6.9590e+03  1e-02  1e-16  2e-06
 2: -6.9590e+03 -6.9590e+03  1e-04  3e-16  2e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -9.4530e+03 -9.4540e+03  1e+00  0e+00  2e-04
 1: -9.4530e+03 -9.4530e+03  1e-02  1e-16  2e-06
 2: -9.4530e+03 -9.4530e+03  1e-04  3e-16  2e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -9.0580e+03 -9.0590e+03  1e+00  2e-16  2e-04
 1: -9.0580e+03 -9.0580e+03  1e-02  2e-16  2e-06
 2: -9.0580e+03 -9.0580e+03  1e-04  0e+00  2e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -5.5860e+03 -5.5870e+03  1e+00  0e+00  2e-04
 1: -5.5860e+03 -5.5860e+03  1e-02  1e-16  2e-06
 2: -5.5860e+03 -5.5860e+03  1e-04  3e-16  2e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0:

     pcost       dcost       gap    pres   dres
 0: -1.0456e+04 -1.0457e+04  1e+00  1e-16  2e-04
 1: -1.0456e+04 -1.0456e+04  1e-02  3e-16  2e-06
 2: -1.0456e+04 -1.0456e+04  1e-04  3e-16  2e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -4.9000e+03 -4.9010e+03  1e+00  1e-16  2e-04
 1: -4.9000e+03 -4.9000e+03  1e-02  3e-16  2e-06
 2: -4.9000e+03 -4.9000e+03  1e-04  3e-16  2e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -1.1136e+04 -1.1137e+04  1e+00  4e-16  2e-04
 1: -1.1136e+04 -1.1136e+04  1e-02  2e-16  2e-06
 2: -1.1136e+04 -1.1136e+04  1e-04  0e+00  2e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -6.6310e+03 -6.6320e+03  1e+00  2e-16  2e-04
 1: -6.6310e+03 -6.6310e+03  1e-02  2e-16  2e-06
 2: -6.6310e+03 -6.6310e+03  1e-04  0e+00  2e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -7.6230e+03 -7.6240e+03  1e+00  0e+00  2e-04
 1: -7.6230e+03 -7.6230e+03

 2: -5.8140e+03 -5.8140e+03  1e-04  3e-16  3e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -8.1880e+03 -8.1890e+03  1e+00  3e-16  2e-04
 1: -8.1880e+03 -8.1880e+03  1e-02  0e+00  2e-06
 2: -8.1880e+03 -8.1880e+03  1e-04  1e-16  2e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -1.0432e+04 -1.0433e+04  1e+00  1e-16  2e-04
 1: -1.0432e+04 -1.0432e+04  1e-02  3e-16  2e-06
 2: -1.0432e+04 -1.0432e+04  1e-04  3e-16  2e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -1.5124e+04 -1.5125e+04  1e+00  4e-16  1e-04
 1: -1.5124e+04 -1.5124e+04  1e-02  2e-16  1e-06
 2: -1.5124e+04 -1.5124e+04  1e-04  0e+00  1e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -8.2150e+03 -8.2160e+03  1e+00  2e-16  2e-04
 1: -8.2150e+03 -8.2150e+03  1e-02  3e-16  2e-06
 2: -8.2150e+03 -8.2150e+03  1e-04  3e-16  2e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0:

 1: -5.0890e+03 -5.0890e+03  1e-02  1e-16  3e-06
 2: -5.0890e+03 -5.0890e+03  1e-04  3e-16  3e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -9.1880e+03 -9.1890e+03  1e+00  1e-16  2e-04
 1: -9.1880e+03 -9.1880e+03  1e-02  3e-16  2e-06
 2: -9.1880e+03 -9.1880e+03  1e-04  3e-16  2e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -1.1845e+04 -1.1846e+04  1e+00  0e+00  1e-04
 1: -1.1845e+04 -1.1845e+04  1e-02  1e-16  1e-06
 2: -1.1845e+04 -1.1845e+04  1e-04  3e-16  1e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -5.0860e+03 -5.0870e+03  1e+00  1e-16  3e-04
 1: -5.0860e+03 -5.0860e+03  1e-02  3e-16  3e-06
 2: -5.0860e+03 -5.0860e+03  1e-04  3e-16  3e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -2.5290e+03 -2.5300e+03  1e+00  2e-16  4e-04
 1: -2.5290e+03 -2.5290e+03  1e-02  2e-16  4e-06
 2: -2.5290e+03 -2.5290e+03  1e-04  0e+00  4e-08
Optimal solution found.
  

 1: -1.4364e+04 -1.4364e+04  1e-02  0e+00  1e-06
 2: -1.4364e+04 -1.4364e+04  1e-04  1e-16  1e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -9.0300e+03 -9.0310e+03  1e+00  2e-16  2e-04
 1: -9.0300e+03 -9.0300e+03  1e-02  2e-16  2e-06
 2: -9.0300e+03 -9.0300e+03  1e-04  0e+00  2e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -4.3270e+03 -4.3280e+03  1e+00  2e-16  3e-04
 1: -4.3270e+03 -4.3270e+03  1e-02  3e-16  3e-06
 2: -4.3270e+03 -4.3270e+03  1e-04  3e-16  3e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -1.1710e+04 -1.1711e+04  1e+00  2e-16  1e-04
 1: -1.1710e+04 -1.1710e+04  1e-02  2e-16  1e-06
 2: -1.1710e+04 -1.1710e+04  1e-04  0e+00  1e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -8.7120e+03 -8.7130e+03  1e+00  2e-16  2e-04
 1: -8.7120e+03 -8.7120e+03  1e-02  2e-16  2e-06
 2: -8.7120e+03 -8.7120e+03  1e-04  0e+00  2e-08
Optimal solution found.
  

 0: -5.5590e+03 -5.5600e+03  1e+00  0e+00  3e-04
 1: -5.5590e+03 -5.5590e+03  1e-02  1e-16  3e-06
 2: -5.5590e+03 -5.5590e+03  1e-04  3e-16  3e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -9.2220e+03 -9.2230e+03  1e+00  4e-16  2e-04
 1: -9.2220e+03 -9.2220e+03  1e-02  2e-16  2e-06
 2: -9.2220e+03 -9.2220e+03  1e-04  0e+00  2e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -7.9270e+03 -7.9280e+03  1e+00  0e+00  2e-04
 1: -7.9270e+03 -7.9270e+03  1e-02  1e-16  2e-06
 2: -7.9270e+03 -7.9270e+03  1e-04  3e-16  2e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -6.3770e+03 -6.3780e+03  1e+00  0e+00  3e-04
 1: -6.3770e+03 -6.3770e+03  1e-02  1e-16  3e-06
 2: -6.3770e+03 -6.3770e+03  1e-04  3e-16  3e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -1.1975e+04 -1.1976e+04  1e+00  2e-16  1e-04
 1: -1.1975e+04 -1.1975e+04  1e-02  2e-16  1e-06
 2: -1.1975e+04 -1.1975e+0

     pcost       dcost       gap    pres   dres
 0: -1.0671e+04 -1.0672e+04  1e+00  0e+00  2e-04
 1: -1.0671e+04 -1.0671e+04  1e-02  1e-16  2e-06
 2: -1.0671e+04 -1.0671e+04  1e-04  3e-16  2e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -3.4670e+03 -3.4680e+03  1e+00  0e+00  3e-04
 1: -3.4670e+03 -3.4670e+03  1e-02  1e-16  3e-06
 2: -3.4670e+03 -3.4670e+03  1e-04  3e-16  3e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -9.8660e+03 -9.8670e+03  1e+00  2e-16  2e-04
 1: -9.8660e+03 -9.8660e+03  1e-02  3e-16  2e-06
 2: -9.8660e+03 -9.8660e+03  1e-04  3e-16  2e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -1.1928e+04 -1.1929e+04  1e+00  3e-16  1e-04
 1: -1.1928e+04 -1.1928e+04  1e-02  0e+00  1e-06
 2: -1.1928e+04 -1.1928e+04  1e-04  1e-16  1e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -4.6660e+03 -4.6670e+03  1e+00  1e-16  3e-04
 1: -4.6660e+03 -4.6660e+03

     pcost       dcost       gap    pres   dres
 0: -6.9650e+03 -6.9660e+03  1e+00  2e-16  2e-04
 1: -6.9650e+03 -6.9650e+03  1e-02  2e-16  2e-06
 2: -6.9650e+03 -6.9650e+03  1e-04  0e+00  2e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -1.2262e+04 -1.2263e+04  1e+00  2e-16  1e-04
 1: -1.2262e+04 -1.2262e+04  1e-02  2e-16  1e-06
 2: -1.2262e+04 -1.2262e+04  1e-04  0e+00  1e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -7.1900e+03 -7.1910e+03  1e+00  4e-16  2e-04
 1: -7.1900e+03 -7.1900e+03  1e-02  2e-16  2e-06
 2: -7.1900e+03 -7.1900e+03  1e-04  0e+00  2e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -6.2910e+03 -6.2920e+03  1e+00  2e-16  2e-04
 1: -6.2910e+03 -6.2910e+03  1e-02  2e-16  2e-06
 2: -6.2910e+03 -6.2910e+03  1e-04  0e+00  2e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -1.1288e+04 -1.1289e+04  1e+00  2e-16  2e-04
 1: -1.1288e+04 -1.1288e+04

     pcost       dcost       gap    pres   dres
 0: -6.5140e+03 -6.5150e+03  1e+00  1e-16  2e-04
 1: -6.5140e+03 -6.5140e+03  1e-02  3e-16  2e-06
 2: -6.5140e+03 -6.5140e+03  1e-04  3e-16  2e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -7.6780e+03 -7.6790e+03  1e+00  3e-16  2e-04
 1: -7.6780e+03 -7.6780e+03  1e-02  0e+00  2e-06
 2: -7.6780e+03 -7.6780e+03  1e-04  1e-16  2e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -8.2580e+03 -8.2590e+03  1e+00  2e-16  2e-04
 1: -8.2580e+03 -8.2580e+03  1e-02  3e-16  2e-06
 2: -8.2580e+03 -8.2580e+03  1e-04  3e-16  2e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -8.0390e+03 -8.0400e+03  1e+00  0e+00  2e-04
 1: -8.0390e+03 -8.0390e+03  1e-02  1e-16  2e-06
 2: -8.0390e+03 -8.0390e+03  1e-04  3e-16  2e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -5.6490e+03 -5.6500e+03  1e+00  2e-16  3e-04
 1: -5.6490e+03 -5.6490e+03

 2: -1.4364e+04 -1.4364e+04  1e-04  1e-16  1e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -1.4977e+04 -1.4978e+04  1e+00  2e-16  1e-04
 1: -1.4977e+04 -1.4977e+04  1e-02  2e-16  1e-06
 2: -1.4977e+04 -1.4977e+04  1e-04  0e+00  1e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -7.3020e+03 -7.3030e+03  1e+00  4e-16  2e-04
 1: -7.3020e+03 -7.3020e+03  1e-02  2e-16  2e-06
 2: -7.3020e+03 -7.3020e+03  1e-04  0e+00  2e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -1.1545e+04 -1.1546e+04  1e+00  2e-16  1e-04
 1: -1.1545e+04 -1.1545e+04  1e-02  2e-16  1e-06
 2: -1.1545e+04 -1.1545e+04  1e-04  0e+00  1e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -1.3779e+04 -1.3780e+04  1e+00  2e-16  1e-04
 1: -1.3779e+04 -1.3779e+04  1e-02  3e-16  1e-06
 2: -1.3779e+04 -1.3779e+04  1e-04  3e-16  1e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0:

     pcost       dcost       gap    pres   dres
 0: -1.3715e+04 -1.3716e+04  1e+00  2e-16  1e-04
 1: -1.3715e+04 -1.3715e+04  1e-02  3e-16  1e-06
 2: -1.3715e+04 -1.3715e+04  1e-04  3e-16  1e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -1.2654e+04 -1.2655e+04  1e+00  1e-16  1e-04
 1: -1.2654e+04 -1.2654e+04  1e-02  3e-16  1e-06
 2: -1.2654e+04 -1.2654e+04  1e-04  3e-16  1e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -1.2131e+04 -1.2132e+04  1e+00  2e-16  1e-04
 1: -1.2131e+04 -1.2131e+04  1e-02  2e-16  1e-06
 2: -1.2131e+04 -1.2131e+04  1e-04  0e+00  1e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -1.1989e+04 -1.1990e+04  1e+00  4e-16  1e-04
 1: -1.1989e+04 -1.1989e+04  1e-02  2e-16  1e-06
 2: -1.1989e+04 -1.1989e+04  1e-04  0e+00  1e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -7.9570e+03 -7.9580e+03  1e+00  2e-16  2e-04
 1: -7.9570e+03 -7.9570e+03

     pcost       dcost       gap    pres   dres
 0: -8.7870e+03 -8.7880e+03  1e+00  1e-16  2e-04
 1: -8.7870e+03 -8.7870e+03  1e-02  3e-16  2e-06
 2: -8.7870e+03 -8.7870e+03  1e-04  3e-16  2e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -1.0747e+04 -1.0748e+04  1e+00  0e+00  2e-04
 1: -1.0747e+04 -1.0747e+04  1e-02  1e-16  2e-06
 2: -1.0747e+04 -1.0747e+04  1e-04  3e-16  2e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -5.3010e+03 -5.3020e+03  1e+00  0e+00  3e-04
 1: -5.3010e+03 -5.3010e+03  1e-02  1e-16  3e-06
 2: -5.3010e+03 -5.3010e+03  1e-04  3e-16  3e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -9.9130e+03 -9.9140e+03  1e+00  1e-16  2e-04
 1: -9.9130e+03 -9.9130e+03  1e-02  3e-16  2e-06
 2: -9.9130e+03 -9.9130e+03  1e-04  3e-16  2e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -9.7710e+03 -9.7720e+03  1e+00  1e-16  2e-04
 1: -9.7710e+03 -9.7710e+03

 2: -1.0680e+04 -1.0680e+04  1e-04  0e+00  2e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -7.8450e+03 -7.8460e+03  1e+00  2e-16  2e-04
 1: -7.8450e+03 -7.8450e+03  1e-02  3e-16  2e-06
 2: -7.8450e+03 -7.8450e+03  1e-04  3e-16  2e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -7.6910e+03 -7.6920e+03  1e+00  0e+00  2e-04
 1: -7.6910e+03 -7.6910e+03  1e-02  1e-16  2e-06
 2: -7.6910e+03 -7.6910e+03  1e-04  3e-16  2e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -6.2130e+03 -6.2140e+03  1e+00  0e+00  3e-04
 1: -6.2130e+03 -6.2130e+03  1e-02  1e-16  3e-06
 2: -6.2130e+03 -6.2130e+03  1e-04  3e-16  3e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -4.6010e+03 -4.6020e+03  1e+00  1e-16  3e-04
 1: -4.6010e+03 -4.6010e+03  1e-02  3e-16  3e-06
 2: -4.6010e+03 -4.6010e+03  1e-04  3e-16  3e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0:

 1: -1.1806e+04 -1.1806e+04  1e-02  1e-16  1e-06
 2: -1.1806e+04 -1.1806e+04  1e-04  3e-16  1e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -1.4300e+04 -1.4301e+04  1e+00  7e-16  1e-04
 1: -1.4300e+04 -1.4300e+04  1e-02  3e-16  1e-06
 2: -1.4300e+04 -1.4300e+04  1e-04  1e-16  1e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -8.4110e+03 -8.4120e+03  1e+00  1e-16  2e-04
 1: -8.4110e+03 -8.4110e+03  1e-02  3e-16  2e-06
 2: -8.4110e+03 -8.4110e+03  1e-04  3e-16  2e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -1.0864e+04 -1.0865e+04  1e+00  2e-16  2e-04
 1: -1.0864e+04 -1.0864e+04  1e-02  2e-16  2e-06
 2: -1.0864e+04 -1.0864e+04  1e-04  0e+00  2e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -1.0297e+04 -1.0298e+04  1e+00  0e+00  2e-04
 1: -1.0297e+04 -1.0297e+04  1e-02  1e-16  2e-06
 2: -1.0297e+04 -1.0297e+04  1e-04  3e-16  2e-08
Optimal solution found.
  

 2: -1.5413e+04 -1.5413e+04  1e-04  3e-16  1e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -6.4660e+03 -6.4670e+03  1e+00  4e-16  2e-04
 1: -6.4660e+03 -6.4660e+03  1e-02  2e-16  2e-06
 2: -6.4660e+03 -6.4660e+03  1e-04  0e+00  2e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -1.3111e+04 -1.3112e+04  1e+00  0e+00  1e-04
 1: -1.3111e+04 -1.3111e+04  1e-02  1e-16  1e-06
 2: -1.3111e+04 -1.3111e+04  1e-04  3e-16  1e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -6.7740e+03 -6.7750e+03  1e+00  2e-16  2e-04
 1: -6.7740e+03 -6.7740e+03  1e-02  2e-16  2e-06
 2: -6.7740e+03 -6.7740e+03  1e-04  0e+00  2e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -1.3303e+04 -1.3304e+04  1e+00  2e-16  1e-04
 1: -1.3303e+04 -1.3303e+04  1e-02  2e-16  1e-06
 2: -1.3303e+04 -1.3303e+04  1e-04  0e+00  1e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0:

     pcost       dcost       gap    pres   dres
 0: -6.4580e+03 -6.4590e+03  1e+00  2e-16  2e-04
 1: -6.4580e+03 -6.4580e+03  1e-02  2e-16  2e-06
 2: -6.4580e+03 -6.4580e+03  1e-04  0e+00  2e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -1.2905e+04 -1.2906e+04  1e+00  2e-16  1e-04
 1: -1.2905e+04 -1.2905e+04  1e-02  3e-16  1e-06
 2: -1.2905e+04 -1.2905e+04  1e-04  3e-16  1e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -3.5490e+03 -3.5500e+03  1e+00  0e+00  4e-04
 1: -3.5490e+03 -3.5490e+03  1e-02  1e-16  4e-06
 2: -3.5490e+03 -3.5490e+03  1e-04  3e-16  4e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -1.0583e+04 -1.0584e+04  1e+00  7e-16  2e-04
 1: -1.0583e+04 -1.0583e+04  1e-02  3e-16  2e-06
 2: -1.0583e+04 -1.0583e+04  1e-04  1e-16  2e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -1.1875e+04 -1.1876e+04  1e+00  2e-16  2e-04
 1: -1.1875e+04 -1.1875e+04

 0: -7.1570e+03 -7.1580e+03  1e+00  2e-16  2e-04
 1: -7.1570e+03 -7.1570e+03  1e-02  2e-16  2e-06
 2: -7.1570e+03 -7.1570e+03  1e-04  0e+00  2e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -1.5549e+04 -1.5550e+04  1e+00  2e-16  1e-04
 1: -1.5549e+04 -1.5549e+04  1e-02  2e-16  1e-06
 2: -1.5549e+04 -1.5549e+04  1e-04  0e+00  1e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -9.2590e+03 -9.2600e+03  1e+00  2e-16  2e-04
 1: -9.2590e+03 -9.2590e+03  1e-02  2e-16  2e-06
 2: -9.2590e+03 -9.2590e+03  1e-04  0e+00  2e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -9.4650e+03 -9.4660e+03  1e+00  0e+00  2e-04
 1: -9.4650e+03 -9.4650e+03  1e-02  1e-16  2e-06
 2: -9.4650e+03 -9.4650e+03  1e-04  3e-16  2e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -6.2150e+03 -6.2160e+03  1e+00  0e+00  3e-04
 1: -6.2150e+03 -6.2150e+03  1e-02  1e-16  3e-06
 2: -6.2150e+03 -6.2150e+0

 0: -1.0479e+04 -1.0480e+04  1e+00  1e-16  2e-04
 1: -1.0479e+04 -1.0479e+04  1e-02  3e-16  2e-06
 2: -1.0479e+04 -1.0479e+04  1e-04  3e-16  2e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -1.2863e+04 -1.2864e+04  1e+00  2e-16  1e-04
 1: -1.2863e+04 -1.2863e+04  1e-02  2e-16  1e-06
 2: -1.2863e+04 -1.2863e+04  1e-04  0e+00  1e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -8.5850e+03 -8.5860e+03  1e+00  2e-16  2e-04
 1: -8.5850e+03 -8.5850e+03  1e-02  2e-16  2e-06
 2: -8.5850e+03 -8.5850e+03  1e-04  0e+00  2e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -8.4980e+03 -8.4990e+03  1e+00  2e-16  2e-04
 1: -8.4980e+03 -8.4980e+03  1e-02  2e-16  2e-06
 2: -8.4980e+03 -8.4980e+03  1e-04  0e+00  2e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -7.1090e+03 -7.1100e+03  1e+00  0e+00  2e-04
 1: -7.1090e+03 -7.1090e+03  1e-02  1e-16  2e-06
 2: -7.1090e+03 -7.1090e+0

 0: -7.8330e+03 -7.8340e+03  1e+00  2e-16  2e-04
 1: -7.8330e+03 -7.8330e+03  1e-02  2e-16  2e-06
 2: -7.8330e+03 -7.8330e+03  1e-04  0e+00  2e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -4.9810e+03 -4.9820e+03  1e+00  2e-16  3e-04
 1: -4.9810e+03 -4.9810e+03  1e-02  2e-16  3e-06
 2: -4.9810e+03 -4.9810e+03  1e-04  0e+00  3e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -1.3649e+04 -1.3650e+04  1e+00  2e-16  1e-04
 1: -1.3649e+04 -1.3649e+04  1e-02  3e-16  1e-06
 2: -1.3649e+04 -1.3649e+04  1e-04  3e-16  1e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -7.4310e+03 -7.4320e+03  1e+00  0e+00  2e-04
 1: -7.4310e+03 -7.4310e+03  1e-02  1e-16  2e-06
 2: -7.4310e+03 -7.4310e+03  1e-04  3e-16  2e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -6.8270e+03 -6.8280e+03  1e+00  1e-16  2e-04
 1: -6.8270e+03 -6.8270e+03  1e-02  3e-16  2e-06
 2: -6.8270e+03 -6.8270e+0

 0: -8.9850e+03 -8.9860e+03  1e+00  4e-16  2e-04
 1: -8.9850e+03 -8.9850e+03  1e-02  2e-16  2e-06
 2: -8.9850e+03 -8.9850e+03  1e-04  0e+00  2e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -1.2697e+04 -1.2698e+04  1e+00  2e-16  1e-04
 1: -1.2697e+04 -1.2697e+04  1e-02  2e-16  1e-06
 2: -1.2697e+04 -1.2697e+04  1e-04  0e+00  1e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -6.9650e+03 -6.9660e+03  1e+00  2e-16  2e-04
 1: -6.9650e+03 -6.9650e+03  1e-02  2e-16  2e-06
 2: -6.9650e+03 -6.9650e+03  1e-04  0e+00  2e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -1.3470e+04 -1.3471e+04  1e+00  0e+00  1e-04
 1: -1.3470e+04 -1.3470e+04  1e-02  1e-16  1e-06
 2: -1.3470e+04 -1.3470e+04  1e-04  3e-16  1e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -6.2430e+03 -6.2440e+03  1e+00  1e-16  3e-04
 1: -6.2430e+03 -6.2430e+03  1e-02  3e-16  3e-06
 2: -6.2430e+03 -6.2430e+0

     pcost       dcost       gap    pres   dres
 0: -7.6830e+03 -7.6840e+03  1e+00  2e-16  2e-04
 1: -7.6830e+03 -7.6830e+03  1e-02  2e-16  2e-06
 2: -7.6830e+03 -7.6830e+03  1e-04  0e+00  2e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -8.2600e+03 -8.2610e+03  1e+00  2e-16  2e-04
 1: -8.2600e+03 -8.2600e+03  1e-02  3e-16  2e-06
 2: -8.2600e+03 -8.2600e+03  1e-04  3e-16  2e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -1.1966e+04 -1.1967e+04  1e+00  2e-16  1e-04
 1: -1.1966e+04 -1.1966e+04  1e-02  3e-16  1e-06
 2: -1.1966e+04 -1.1966e+04  1e-04  3e-16  1e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -1.0486e+04 -1.0487e+04  1e+00  1e-16  2e-04
 1: -1.0486e+04 -1.0486e+04  1e-02  3e-16  2e-06
 2: -1.0486e+04 -1.0486e+04  1e-04  3e-16  2e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -4.1320e+03 -4.1330e+03  1e+00  0e+00  3e-04
 1: -4.1320e+03 -4.1320e+03

     pcost       dcost       gap    pres   dres
 0: -1.1863e+04 -1.1864e+04  1e+00  4e-16  1e-04
 1: -1.1863e+04 -1.1863e+04  1e-02  2e-16  1e-06
 2: -1.1863e+04 -1.1863e+04  1e-04  0e+00  1e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -9.2250e+03 -9.2260e+03  1e+00  2e-16  2e-04
 1: -9.2250e+03 -9.2250e+03  1e-02  2e-16  2e-06
 2: -9.2250e+03 -9.2250e+03  1e-04  0e+00  2e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -9.6400e+03 -9.6410e+03  1e+00  2e-16  2e-04
 1: -9.6400e+03 -9.6400e+03  1e-02  2e-16  2e-06
 2: -9.6400e+03 -9.6400e+03  1e-04  0e+00  2e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -2.7780e+03 -2.7790e+03  1e+00  0e+00  5e-04
 1: -2.7780e+03 -2.7780e+03  1e-02  1e-16  5e-06
 2: -2.7780e+03 -2.7780e+03  1e-04  3e-16  5e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -9.0080e+03 -9.0090e+03  1e+00  2e-16  2e-04
 1: -9.0080e+03 -9.0080e+03

     pcost       dcost       gap    pres   dres
 0: -8.0110e+03 -8.0120e+03  1e+00  0e+00  2e-04
 1: -8.0110e+03 -8.0110e+03  1e-02  1e-16  2e-06
 2: -8.0110e+03 -8.0110e+03  1e-04  3e-16  2e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -5.7420e+03 -5.7430e+03  1e+00  0e+00  3e-04
 1: -5.7420e+03 -5.7420e+03  1e-02  1e-16  3e-06
 2: -5.7420e+03 -5.7420e+03  1e-04  3e-16  3e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -1.4624e+04 -1.4625e+04  1e+00  0e+00  1e-04
 1: -1.4624e+04 -1.4624e+04  1e-02  1e-16  1e-06
 2: -1.4624e+04 -1.4624e+04  1e-04  3e-16  1e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -1.1068e+04 -1.1069e+04  1e+00  2e-16  2e-04
 1: -1.1068e+04 -1.1068e+04  1e-02  3e-16  2e-06
 2: -1.1068e+04 -1.1068e+04  1e-04  3e-16  2e-08
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -1.0116e+04 -1.0117e+04  1e+00  0e+00  2e-04
 1: -1.0116e+04 -1.0116e+04

ValueError: Rank(A) < p or Rank([P; A; G]) < n

In [319]:
from cvxopt import matrix, solvers
k = 3
i = 0
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.5)
test_num = len(x_test)
y_predict = np.zeros(test_num)

distance = np.sum(np.square(x_train - x_test[i,:]), axis=1)
nearest_idx = np.argpartition(distance, [0, k-1])[0:k]
k_neighbors = x_train[nearest_idx]
distance = np.sum(np.square(k_neighbors - x_test[i,:]), axis=1)

p=np.zeros((k, k))
q=np.zeros((k, 1))
for m in range(k):
    q[m][0] = -2*np.sum(k_neighbors[m] * x_test[i])
    for n in range(k):
        p[m][n] = 2*np.sum(k_neighbors[m] * k_neighbors[n])

g = -1*np.identity(k)
h = np.zeros((k, 1))
a = np.ones((1,k))


In [320]:
distance

array([11536, 11800, 11998], dtype=uint32)

In [321]:
x_test[i,:]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0, 249, 254, 255, 254, 191, 254, 254, 254,
       210,  89,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0, 248, 253, 253, 253, 106, 157,
       204, 253, 253, 248, 211,  37,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,  40,  40,  4

In [322]:
k_neighbors[0, :]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   

In [323]:
p


array([[3226., 6948., 8366.],
       [6948., 4042., 8156.],
       [8366., 8156., 4814.]])

In [324]:
q

array([[-12052.],
       [-12708.],
       [-16480.]])

In [315]:
g

array([[-1., -0.],
       [-0., -1.]])

In [316]:
h

array([[0.],
       [0.]])

In [317]:
a

array([[1., 1.]])

In [318]:
P=matrix(p)
q=matrix(q)
G=matrix(g)
h=matrix(h)
A=matrix(a)
b=matrix([1.0])
w=np.squeeze(solvers.qp(P,q,G,h,A,b)['x'])
votes = np.squeeze(y_train[nearest_idx])
if k == 1:
    votes = np.array([votes])
    w = np.array([1])
y_predict[i] = np.argmax(np.bincount(votes, weights=w))

ValueError: Rank(A) < p or Rank([P; A; G]) < n

In [325]:
x = np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [327]:
y = np.array([5,6,7,8])
y

array([5, 6, 7, 8])

In [328]:
x*y

array([ 5, 12, 21, 32])

In [329]:
np.sum(x*y)

70

In [337]:
k_neighbors[0]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   

In [339]:
g[0][1]

-0.0